image: php:5.6

cache:
    paths:
        - vendor/

before_script:
    # Install dependencies
- bash ci/docker_install.sh > /dev/null
- curl --silent --show-error https://getcomposer.org/installer | php
- php composer.phar install

services:
    - mysql

variables:
# Configure mysql service (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: web_user
    MYSQL_ROOT_PASSWORD: web_user

test:app:
  script:
  - php oil test --group=App --debug